### ISSUE TITLE
Stacks of certain food items are consumed all at once instead of one at a time

### ISSUE THREAD

**Issue by Samarai** [ValleyCraft-Dev-Team/ValleyCraft-Wiki#13]
Some food items, like Hot Cocoa and Large Pancake Breakfasts (haven't tested with other items yet) are able to be stacked, but will be completely used up and give you the effects of having only had one of the food items, including only returning one bowl or mug.

**Comment by l1nkl3** [comment]
we've fixed this in version 2.2 which will be released very soon
